branch-defaults:
  master:
    environment: production
    group_suffix: null
  post_rich_fixes:
    environment: staging
  staging:
    environment: ruby3staging
environment-defaults:
  staging:
    branch: null
    repository: null
global:
  application_name: policeboard
  branch: null
  default_ec2_keyname: steves
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
